// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPItest.Models;

#nullable disable

namespace WebAPItest.Migrations
{
    [DbContext(typeof(A01Context))]
    partial class A01ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPItest.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("branchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchName");

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brandId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("BranchId")
                        .HasName("PK__Branch__751EBD5F33FA43BF");

                    b.HasIndex("BrandId");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("WebAPItest.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("brandId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Brand1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("brand");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("logo");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("url");

                    b.HasKey("BrandId")
                        .HasName("PK__Brand__06B772995AD10E28");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("WebAPItest.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favoriteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int")
                        .HasColumnName("furnitureId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("userId");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__876A64D58AA15765");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("WebAPItest.Models.Furniture", b =>
                {
                    b.Property<int>("FurnitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("furnitureId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FurnitureId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brandId");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("Location")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("location");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("picture");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("style");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("FurnitureId")
                        .HasName("PK__Furnitur__BD41E4C50FA6B547");

                    b.HasIndex("BrandId");

                    b.ToTable("Furniture", (string)null);
                });

            modelBuilder.Entity("WebAPItest.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("messageId");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int")
                        .HasColumnName("furnitureId");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("userId");

                    b.HasKey("MessageId")
                        .HasName("PK__Message__4808B9933BCF5750");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("WebAPItest.Models.Branch", b =>
                {
                    b.HasOne("WebAPItest.Models.Brand", "Brand")
                        .WithMany("Branches")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__Branch__brandId__4E88ABD4");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("WebAPItest.Models.Favorite", b =>
                {
                    b.HasOne("WebAPItest.Models.Furniture", "Furniture")
                        .WithMany("Favorites")
                        .HasForeignKey("FurnitureId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorite__furnit__59FA5E80");

                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("WebAPItest.Models.Furniture", b =>
                {
                    b.HasOne("WebAPItest.Models.Brand", "Brand")
                        .WithMany("Furnitures")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__Furniture__brand__571DF1D5");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("WebAPItest.Models.Message", b =>
                {
                    b.HasOne("WebAPItest.Models.Furniture", "Furniture")
                        .WithMany("Messages")
                        .HasForeignKey("FurnitureId")
                        .IsRequired()
                        .HasConstraintName("FK__Message__furnitu__5CD6CB2B");

                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("WebAPItest.Models.Brand", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("WebAPItest.Models.Furniture", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
